In [1]:
import numpy as np

# 1. Načtení dat

In [3]:
data = np.load("pacienti.npy")

print("Tvar pole:", data.shape)
print("Prvních 5 radku:\n", data[:5])

Tvar pole: (20, 3)
Prvních 5 radku:
 [[129.6  78.2  93. ]
 [109.4  73.2  72. ]
 [136.3  92.2  61. ]
 [139.1  78.5  89. ]
 [ 95.7  75.7  80. ]]


# 2. Průměr a směrodatná odchylka každého ukazatele

In [4]:
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)

print("\nPrůměry (systolický, diastolický, tep):", mean)
print("Směrodatné odchylky:", std)


Průměry (systolický, diastolický, tep): [124.51   81.105  77.   ]
Směrodatné odchylky: [12.72807527  7.73869983 11.28273017]


# 3. Pacienti s hypertenzí (systolický ≥ 140)

In [ ]:
hypertenze = data[data[:, 0] >= 140]

print("\nPočet pacientů s hypertenzí:", len(hypertenze))

if len(hypertenze) > 0:
    avg_sys = np.mean(hypertenze[:, 0])
    print("Průměrný systolický tlak (hypertenze):", avg_sys)

# 4. Pulzní tlak jako nový sloupec

In [31]:
pulzni_tlak = data[:, 0] - data[:, 1]
data_ext = np.column_stack((data, pulzni_tlak))

print("\nData s pulzním tlakem:\n", data_ext[:5])


Data s pulzním tlakem:
 [[129.6  78.2  93.   51.4]
 [109.4  73.2  72.   36.2]
 [136.3  92.2  61.   44.1]
 [139.1  78.5  89.   60.6]
 [ 95.7  75.7  80.   20. ]]


# 5. Pacient s nejvyšší tepovou frekvencí

In [32]:
idx_max_tep = np.argmax(data[:, 2])
pacient_max_tep = data[idx_max_tep]

print("\nIndex pacienta s nejvyšším tepem:", idx_max_tep)
print("Záznam pacienta:", pacient_max_tep)


Index pacienta s nejvyšším tepem: 0
Záznam pacienta: [129.6  78.2  93. ]
